on:
  push:
    branches: [ master ]

jobs:
  contributors_to_file:
    runs-on: ubuntu-latest
    name: Write contributors to file
    steps:
    - name: Checkout repo
      id: checkout
      uses: actions/checkout@v2
    - name: Update contributors
      id: update_contributors
      uses: TheLastProject/contributors-to-file-action@v1.0.2
      with:
        file_in_repo: app/src/main/res/raw/contributors.txt
